services:
  api:
    build:
      context: ./FCBankDemo   # folder gde se nalazi Dockerfile
      dockerfile: Dockerfile
    container_name: banking-api
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://0.0.0.0:8080"
      ConnectionStrings__DefaultConnection: "Host=host.docker.internal;Port=5432;Database=bankingDb;Username=bankingUser;Password=123"
