FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY ["FCBankDemo.csproj", "./"]
RUN dotnet restore "FCBankDemo.csproj"
COPY . .
RUN dotnet build "FCBankDemo.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "FCBankDemo.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .

# ENTRYPOINT
ENTRYPOINT ["dotnet", "FCBankDemo.dll"]
